chore: move unbound impl generics to their functions (AztecProtocol/aztec-packages#13147)
In Rust, a code like this:

```rust
trait Serialize<U> {}

struct PublicMutable<T>
{
    x: T,
}

impl<T, U> PublicMutable<T>
where
    T: Serialize<U>,
{
    fn serialize() {}
}
```

fails to compile and gives this error:

```
error[E0207]: the type parameter `U` is not constrained by the impl trait, self type, or predicates
 --> src/main.rs:8:9
  |
8 | impl<T, U> PublicMutable<T>
  |         ^ unconstrained type parameter
```

I'm not exactly sure of the technicalities here, there's an explanation
[here](https://stackoverflow.com/a/78258009), but the solution in Rust
is to move the constrains to the relevant functions.

Noir will eventually do the same thing (see
https://github.com/noir-lang/noir/pull/6388 ) so this PR fixes the code
that will eventually stop to compile.

Co-authored-by: Tom French <15848336+TomAFrench@users.noreply.github.com>