fix: Syntax error when running tests via jest after tsc build (AztecProtocol/aztec-packages#13051)
Running e2e tests in jest after building using `tsc -b` would result in
an error `SyntaxError: 'super' keyword unexpected here`.

```
 FAIL  src/e2e_block_building.test.ts
  ● Test suite failed to run

    SyntaxError: 'super' keyword unexpected here

      at Runtime.loadEsmModule (../../node_modules/jest-runtime/build/index.js:517:20)
```

After patching jest to report where the issue was coming up, it turned
out it was caused by the usage of `super` in a js private method. For
some reason tsc was emitting the following:

```ts
  async #getHintKey(treeId: MerkleTreeId): Promise<AppendOnlyTreeSnapshot> {
    const treeInfo = await super.getTreeInfo(treeId);
    return new AppendOnlyTreeSnapshot(Fr.fromBuffer(treeInfo.root), Number(treeInfo.size));
  }
```

```js
_HintingPublicTreesDB_instances = new WeakSet(), _HintingPublicTreesDB_getHintKey =
// Private methods.
async function _HintingPublicTreesDB_getHintKey(treeId) {
    const treeInfo = await super.getTreeInfo(treeId);
    return new AppendOnlyTreeSnapshot(Fr.fromBuffer(treeInfo.root), Number(treeInfo.size));
};
```

Since the private method was moved outside the class as part of code
generation, node threw a syntax error since `super` can only be used in
the context of a class.

This patches the issue by using regular ts private methods, but we still
need to figure out why ts is emitting invalid js code.