fix: bump timeouts in fetch. enable logging. no retry (AztecProtocol/aztec-packages#6831)
Fixes:
```
Error in command execution
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at defaultFetch (file:///Users/mitch/aztec-clones/bravo/yarn-project/foundation/src/json-rpc/client/json_rpc_client.ts:42:12)
    at retry (file:///Users/mitch/aztec-clones/bravo/yarn-project/foundation/src/retry/index.ts:56:14)
    at file:///Users/mitch/aztec-clones/bravo/yarn-project/foundation/src/json-rpc/client/json_rpc_client.ts:78:12
    at request (file:///Users/mitch/aztec-clones/bravo/yarn-project/foundation/src/json-rpc/client/json_rpc_client.ts:116:17)
    at DeployAccountMethod.prove (file:///Users/mitch/aztec-clones/bravo/yarn-project/aztec.js/src/contract/base_contract_interaction.ts:49:15)
    at file:///Users/mitch/aztec-clones/bravo/yarn-project/aztec.js/src/contract/base_contract_interaction.ts:64:30
    at createAccount (file:///Users/mitch/aztec-clones/bravo/yarn-project/cli/src/cmds/create_account.ts:38:22)
    at Command.<anonymous> (file:///Users/mitch/aztec-clones/bravo/yarn-project/cli/src/index.ts:236:7)
    at Command.parseAsync (/Users/mitch/aztec-clones/bravo/yarn-project/node_modules/commander/lib/command.js:935:5) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:8228:32)
      at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:6310:17)
      at listOnTimeout (node:internal/timers:569:17)
      at processTimers (node:internal/timers:512:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```